name: Fix package.json
on:
  pull_request:

jobs:
  fix_package_json:
    name: Fix package.json
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Fix package.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          node scripts/generate-exports.js
          git add package.json
          git commit -m "chore: fix package.json exports" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
