name: Fix package.json
on:
  pull_request:

jobs:
  fix_package_json:
    name: Fix package.json
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Fix package.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.head.ref }}
          git branch --force ${{ github.event.pull_request.head.ref }} --track origin/${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          node scripts/generate-exports.js
          git add package.json
          git commit -am "chore: fix package.json exports" --no-verify || echo "No changes to commit"
          git push
