on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
          release-type: node
          include-component-in-tag: true
        # The logic below handles the npm publication:
      - uses: actions/checkout@v6
        # these if statements ensure that a publication only occurs when
        # a new release is created:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm update -g npm
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run prepack
      - run: |
          ls -a
          ls -a ~
          npm whoami
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ""
