on:
  pull_request:

name: release-please

jobs:
  release-please:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
        # The logic below handles the npm publication:
      - uses: actions/checkout@v6
        # these if statements ensure that a publication only occurs when
        # a new release is created:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - run: npm run prepack
      - run: npm publish --access public --dry-run
